version: '3.7'

services:
  php:
    build: ./php
    volumes:
      - ./public_html:/var/www/html
    networks:
      - webnet

  nginx:
    image: nginx:1.25.0
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www/html
    networks:
      - webnet
    depends_on:
      - php
      - mysql
    
  mysql:
    platform: linux/x86_64 # M1 MAc 対応
    image: mysql:5.7.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:

